[package]
name = "axion-core"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.32"
rayon = "1.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
numquant = "0.2"
bytemuck = "1.13.1"
